#ifndef __FRAMEWORK_PROTOCOL_H__
#define __FRAMEWORK_PROTOCOL_H__
#include "CoreProtocol.h"

namespace framework_proto {
	enum {
		START = core_proto::END,

		BIND_ACCOUNT_REQ,
		BIND_ACCOUNT_ACK,
		UNBIND_ACCOUNT,
		KICK_FROM_ACCOUNT,
		DISTRIBUTE_LOGIC_REQ,
		DISTRIBUTE_LOGIC_ACK,
		BIND_PLAYER,
		UNBIND_PLAYER,
		KICK_FROM_LOGIC,
		TRANSMIT_TO_LOGIC,
		TRANSMIT_TO_ACTOR,

		RPCNR,
		RPC,
		RESPONE,

		END,
	};
}

#endif //__USER_NODE_PROTOCOL_H__
